### ISSUE TITLE
Some question about this extension.

### ISSUE THREAD

**Issue by cyj98** [plussub/plussub#12]
1. How to make this extension work without using shadow dom? 
When I remove attachShadow the extension will malfunction and become transparent. I want to make a new branch in my forked repo without using shadow dom maintained by myself as many other web extension like yomichan cannot work on shadow dom.
2. I find that when I click the extension, it doesn’t popup on Firefox. Do you have the same problem?

**Comment by ste-xx** [comment]
1) you can't*. At least without breaking pages like youtube. With shadowDom you have a kind of isolation. For example you can ensure (in boundaries) that content css will not affect the extension.

Maybe it could work, if the html elements defines many css property and nothing relevant will be inherent from the content document.

*) I tried to ensure the encapsulation with an iframe. But it opens new Problems. Mostly with interaction between extension iframe and content iframe. The typical cors stuff...

2) I will check it today

**Comment by ste-xx** [comment]
Anyway, I think I will redesign the current popup window. 
There is more than one user feedback, that shows that the current ux flow is ambiguous

**Comment by cyj98** [comment]
Sure, you can contact me at my email: cyj98cn@yahoo.com
Or maybe it’s better to use IM. You can tell me your favorite IM software and I will try to install it.

**Comment by cyj98** [comment]
I found how to make this extension work without shadow dom now. I just need to change :host() to #plussubShadow and change some code in usedraggablearea and change <style> to <style scope>.
Maybe it’s no need to use shadow dom in this extension. Scoped CSS is already a substitute for style encapsulation found in Shadow DOM. Using scoped CSS is enough for this extension.

**Comment by cyj98** [comment]
I found how to make this extension work without shadow dom now. I just need to change :host() to #plussubShadow, change some code in usedraggablearea and change some <style> to <style scoped>.
Maybe there's no need to use shadow dom in this extension. Scoped CSS is already a substitute for style encapsulation in Shadow DOM which can ensure the website's css content not affect the extension. I can just change all <style> to <style scoped> except <style> with CSS custom properties which is scoped in the element that define the variable. I think using scoped CSS is enough for this extension.

**Comment by ste-xx** [comment]
Is this really an issue with shadow dom or is it a drawback because plussub calls preventsDefault() on keydown events (only in plussub inputfields).

The reason for the preventDefault is, that otherwise youtube and vimeo shortcuts come into action. Like f for fullscreen which is really annoying.

**Comment by ste-xx** [comment]
BTW: you are right, something is wrong with firefox

**Comment by ste-xx** [comment]
ah i see it now, the alias for firefox are broken.

**Comment by ste-xx** [comment]
firefox should work now.

**Comment by cyj98** [comment]
If just for CSS, scoped CSS and using nesting with the help of scss is enough.
I will check for preventDefault now.

**Comment by cyj98** [comment]
It's nothing to be with preventsDefault(). I have tested and check it in MDN web docs, which shows that some functions cannot work on shadow dom from outside even if it's in open mode, indeed.
I have tried using scoped CSS and SCSS instead of shadow dom and it has worked perfectly by far.

**Comment by cyj98** [comment]
Firefox works now. But the font awesome icons seem to be not shown properly.

**Comment by cyj98** [comment]
I am wrong. The style will be affected by outer style without shadow dom.
I will just keep the no shadow dom version on my own local branch.
