### ISSUE TITLE
Hide/Show Current Subtitle

### ISSUE THREAD

**Issue by ozanmeral** [plussub/plussub#19]
Is there a feature to Hide/Show current subtitle?

**Comment by ste-xx** [comment]
Currently there are following possibilities: 
- Remove the subtitle with the +Sub popup
- If the video is a html5 native player: 
    The subtitle will be shown under cc. You can simply deselect it there.
    Some customize web player supports also this behaviour.

I hope that helps :)

**Comment by ozanmeral** [comment]
The second one will help, thank you :)
