### ISSUE TITLE
the extension doesnt work with crunchyroll.com

### ISSUE THREAD

**Issue by 01MrHacKeR01** [plussub/plussub#20]
as i said above
there a same sitiuation with another sub dev (this sub translate only using google translate ) i told him the same problem and he solved it check it if u got trouble :https://github.com/muzuiget/dualsub-support/issues/127

**Comment by ste-xx** [comment]
Thanks for the feedback, i will take a look

**Comment by Phoenomenal** [comment]
Having the same problem with crunchyroll.   Thats why i use 2 version of the extension ( 1 from chrome store for streaming sites and the other  +Sub 4.7.0 its   the last  working version  with crunchyroll )      

Would be great if it can be fixed in newer releases  because the extension becoming more and more awesome  with each release esprcially since adding support for .ass and .ssa

**Comment by ste-xx** [comment]
Hi,
with the current version 4.18.3, it should work.
At least it works with the preview video. 
e.g.
https://www.crunchyroll.com/black-clover/episode-164-battlefield-heart-kingdom-801385

and if i select the first video. (+Sub shows two videos, i have to investigate that, why is that the case) 

I don't have a premium account, so I can't check if thats also valid for full episodes.

Feedback appreciated. :)

**Comment by Phoenomenal** [comment]
> Hi,
> with the current version 4.18.3, it should work.
> At least it works with the preview video.
> e.g.
> https://www.crunchyroll.com/black-clover/episode-164-battlefield-heart-kingdom-801385
> 
> and if i select the first video. (+Sub shows two videos, i have to investigate that, why is that the case)
> 
> I don't have a premium account, so I can't check if thats also valid for full episodes.
> 
> Feedback appreciated. :)


Hi

version 4.18.3  dont work for me,  i mean not just on crunchyroll but not at all.  No matter what streaming site  the extension window dont popup when i click on it.   The version i use foe a long time  for crunchyroll 4.7.0  works  and also just  downloaded from crx4chrome previous stable version 4.17.1 which also works on all streaming sites    (tested on google chrome version  88.0.4324.182 and microsoft edge dev   90.0.796.0 )

**Comment by ste-xx** [comment]
Thats really strange
i test it with Version 88.0.4324.182 (Offizieller Build) (x86_64) (so like your version) on a mac.

Maybe an interplay with another plugin?

It is really strange that it does not open the popup.

Maybe you can test it on that page: 
https://plussub-test-page.netlify.app/
hit f12
and send me the log after you click on the +sub icon



I used following srt file for testing:

[time.srt.zip](https://github.com/plussub/plussub/files/6029725/time.srt.zip)

**Comment by ste-xx** [comment]
I test crunchyroll.com with following video: 
https://www.crunchyroll.com/black-clover/episode-1-asta-and-yuno-748933 

And it works (at least on my device, with a clean install from the chrome webstore)

@01MrHacKeR01 does crunchyroll.com works now on your device (with +sub version 4.18.3)?

@Phoenomenal I updated to a new chrome extension format. Did you install +sub with the chrome webstore?
https://chrome.google.com/webstore/detail/%2Bsub/lpobdmdfgjokempajoobgfdnhjbjlnpm

**Comment by Phoenomenal** [comment]
> Thats really strange
> i test it with Version 88.0.4324.182 (Offizieller Build) (x86_64) (so like your version) on a mac.
> 
> Maybe an interplay with another plugin?
> 
> It is really strange that it does not open the popup.
> 
> Maybe you can test it on that page:
> https://plussub-test-page.netlify.app/
> hit f12
> and send me the log after you click on the +sub icon
> 
> I used following srt file for testing:
> 
> [time.srt.zip](https://github.com/plussub/plussub/files/6029725/time.srt.zip)

Working in Chrome after i delete all files  and folders  with name  lpobdmdfgjokempajoobgfdnhjbjlnpm   extension in chrome folder.    but still  no popup in Edge .  
Could you possibly make new extension version  work in edge (probably have something to do with  what you write earlier about updated to a new chrome extension format)   ?   

  Crunchyroll is working  on 4.18.3 using chrome.  Thank you very much.
