### ISSUE TITLE
Add support for right to left language. 

### ISSUE THREAD

**Issue by Zion158** [plussub/plussub#23]
Great extension, works well.

**Comment by 01MrHacKeR01** [comment]
> 
> 
> Great extension, works well.

it works good to me but yes there is some problem in names in english and right to left language but that is okay

**Comment by ste-xx** [comment]
@01MrHacKeR01  I try to improve the extension. Which are the problem with names in english? So maybe i can fix that issue :)

**Comment by Zion158** [comment]
Hello,

I'm assuming you can't read Hebrew, but I've added 2 examples from D+
using Edge Sub+ 
Version 4.17.4 January 29, 2021
<img width="742" alt="Hebrew-Error" src="https://user-images.githubusercontent.com/78563756/107708965-15840080-6ccd-11eb-99da-b57bffb1c5f9.png">

**Comment by ste-xx** [comment]
You are right, I can't read hebrew :) But I see the problem. 
Could you add the subtitle here (as .srt or any other format)? That would help me a lot.

**Comment by Zion158** [comment]
Hi,

See attached ZIP file .
Time location for first example 00:09:06,745 --> 00:09:08,413
Time location for second example  00:09:21,676 --> 00:09:23,803
[X-Men.Apocalypse.2016.1080p.BluRay.x264-SECTOR7.zip](https://github.com/plussub/plussub/files/6015156/X-Men.Apocalypse.2016.1080p.BluRay.x264-SECTOR7.zip)

Thanks.

**Comment by ste-xx** [comment]
Hi @Zion158 , 
i really try to wrap my head around that problem :)

I don't know why your subtitle isn't work correctly. I tried also some unicode "magic" to enforce rtl but it doesn't work (in a subtitle, as log output, it seems to work) 

I have here a subtitle which contains following entry
عالي, I think.

That should be rendered as
.think I, عالي

and.... +sub does exactly that.
Maybe you can validate that it works correct? I added the .srt file as zip.

Do you have another subtitle files which this error occure or is it only that one in this ticket? 

[rtl.srt.zip](https://github.com/plussub/plussub/files/6032230/rtl.srt.zip)

**Comment by Zion158** [comment]
Hi,

I've checked the sub, and found out that the Hebrew subtitles are written in left to right.
So your program is working right, but not as should.

can you force left to right on Hebrew text?

<img width="498" alt="Hebrew-punctuations" src="https://user-images.githubusercontent.com/78563756/109218815-8e9c5100-77bf-11eb-9395-879f12dc2de8.png">

Thanks,
Zion

**Comment by ste-xx** [comment]
I will try, but sadly i can't promise anything, because it is really hard for me to investigate that problem. I will have a look how other plugins work around that problem.
