### ISSUE TITLE
funimation not wroking with it u need to inspect video playpack

### ISSUE THREAD

**Issue by 01MrHacKeR01** [plussub/plussub#24]
as it is above 
funimation.com
also there are 2 extensions did that before dualsub had the same problem before
and subsital working with funimation

**Comment by ste-xx** [comment]
Unfortunately funimation.com is not available in my country.
I try to connect with a vpn. But the videos are not playing at all (black screen).

Did you test it with chrome?

**Comment by 01MrHacKeR01** [comment]
> Unfortunately funimation.com is not available in my country.
> I try to connect with a vpn. But the videos are not playing at all (black screen).
> 
> Did you test it with chrome?

use proton vpn it is fast and u can use it by third party app like openvpn i also dont have it in my country but i use vpn
also no he didnt detect video at all u need to inspect and make him recognise it i think
also dualsub extension devloper had this problem too but he first make  a button that make u go to another page where is there the video playpack after that he could find a way to make his extension recognise it in the main page u can check his open source or u or i can ask him how he did it if u had any troubles
