### ISSUE TITLE
answer us and tell us latest news

### ISSUE THREAD

**Issue by 01MrHacKeR01** [plussub/plussub#25]

**Comment by ste-xx** [comment]
?

**Comment by 01MrHacKeR01** [comment]
> What do you want to know? :)

funimation.com support

**Comment by ste-xx** [comment]
I am currently working on it

**Comment by 01MrHacKeR01** [comment]
> I am currently working on it

u can check dualsub extension on dualsub
he wasnt supported it too but he did

**Comment by 01MrHacKeR01** [comment]
> I am currently working on it

i am waiting u to use funimation
also dualsub developer the popularity make him ignore my request and call it waste of time :| SO i am depending on you :)

**Comment by 01MrHacKeR01** [comment]
> I am currently working on it

i am waiting u to use funimation
also dualsub developer the popularity make him ignore my request and call it waste of time :| SO i am depending on you :)

**Comment by ste-xx** [comment]
I'm not ignoring you :)

But I have a full-time job, kids and another duties and pet projects, so that I need some time to fix such issues.

I'm still happy that you report me the issue and like I said before: I'm working on it and it is on the top of my to-do list.

**Comment by ste-xx** [comment]
I have still problems with funimation:

https://windowsreport.com/funimation-not-working-chrome/

@01MrHacKeR01 did you use chrome or another browser?

**Comment by ste-xx** [comment]
Ah I think it is a problem that i use a chrome extension, which works as vpn. (windscribe) :(

**Comment by 01MrHacKeR01** [comment]
> I'm still happy that you report me the issue and like I said before: I'm working on it and it is on the top of my to-do list.

np take ur time
i dont really care but browser i will use as long it works on one of them
also funimation and dualsub were working on chorme extension fine i think
u can try disable windscribe or remove it temp untill u know what is the problem
u can use their program for windows but if it is not working use open vpn connect 
and download their vpn file config from their website just search how to open windscibe on openvpn connect
What exactly is your problem ? explain it more

**Comment by ste-xx** [comment]
The problem is, that funimation says I would use an adblocker. So it doesn't show any video (not even trailer). Instead I got a black screen. 

Now the clue: 
I don't use any adblocker. 
I don't even use any extension except windscribe (vpn client) and i got that adblocker message. 
I need windscribe, because I need a vpn, (funimation is not available in my country).

So I think the only solution where I can help, is to use another vpn client. 

Maybe one which is not a chrome extension...

**Comment by 01MrHacKeR01** [comment]
> windscribe

try another browser and use proton vpn as app or as config file in open vpn connect

**Comment by 01MrHacKeR01** [comment]
> The problem is, that funimation says I would use an adblocker. So it doesn't show any video (not even trailer). Instead I got a black screen.
> 
> Now the clue:
> I don't use any adblocker.
> I don't even use any extension except windscribe (vpn client) and i got that adblocker message.
> I need windscribe, because I need a vpn, (funimation is not available in my country).
> 
> So I think the only solution where I can help, is to use another vpn client.
> 
> Maybe one which is not a chrome extension...

also he o

> The problem is, that funimation says I would use an adblocker. So it doesn't show any video (not even trailer). Instead I got a black screen.
> 
> Now the clue:
> I don't use any adblocker.
> I don't even use any extension except windscribe (vpn client) and i got that adblocker message.
> I need windscribe, because I need a vpn, (funimation is not available in my country).
> 
> So I think the only solution where I can help, is to use another vpn client.
> 
> Maybe one which is not a chrome extension...

also he told me how he add it 
"Funimation and Crunchyrol use <iframe> to show the player, this behavior like embed YouTube player to non-YouTube websites, so you need to handle two page in the same time, in JavaScript, you need to access window.frame object to get the <iframe> page information, this make the code rather complex."
