### ISSUE TITLE
Be Able to Manually Enter Offset Time

### ISSUE THREAD

**Issue by dcruzer231** [plussub/plussub#28]
The offset time cannot be manually entered.  For subtitles delayed beyond +-3000 this can take a while to get to the correct offset time.

**Comment by ste-xx** [comment]
Uh it should be possible :)
Maybe you have to set the input cursor to the start. 
I think there is a glitch that the cursor moves after the 0

**Comment by dcruzer231** [comment]
You are right actually, I tested on a youtube video and I was able to manually enter value.  It seems like this issue is specifically on Hulu then.  That is where I've been using your extension first and for some reason it will not accept manually entered values.  Either from the numpad or the top row.

**Comment by ste-xx** [comment]
Ok i will check it on Hulu
