### ISSUE TITLE
Overlapping subtitles

### ISSUE THREAD

**Issue by ste-xx** [plussub/plussub#34]
the extension just overlaps any lines that run at the same time.

**Comment by Phoenomenal** [comment]
I also noticed that  behaviour.  I believe starting with 6.1 version.   I use  a 6.0.13 version of extension and dont have that problem  with overlaping lines.  And also broken transparency.  Just see an example below :


6.0.13
![Screenshot_6](https://user-images.githubusercontent.com/68902338/150568418-9fe1afd5-84d5-411e-bda0-f95f7ba73ed9.png)


6.1.6
![Screenshot_5](https://user-images.githubusercontent.com/68902338/150568482-efd414be-57f2-4837-854b-8123f32e4412.png)

**Comment by ste-xx** [comment]
Release 6.2.x will fix that issue. 
A new checkbox is added to the customizing tab, which enables snapToLines, which prevents overlapping subtitles. 
If you want to show the subtitle on the bottom, you have to select a high position value, like 94%

**Comment by ste-xx** [comment]
do not show overlapping hint for firefox
