### ISSUE TITLE
Not work on some infamous website

### ISSUE THREAD

**Issue by cyj98** [plussub/plussub#7]
This ext. cannot work on websites like
https://www.agefans.tv/
http://www.yhdm.tv/v/3303-2.html
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs

I have forked this repo and try to make this extension work on more websites but I have no idea how to do it.

**Comment by ste-xx** [comment]
If the video are served via html5 video tags, it should work.
Are the videos correctly detected?

**Comment by cyj98** [comment]
These are all html5 video but in shadow DOM.
When I type document.querySelctor('video') it often return null.

**Comment by cyj98** [comment]
It's clearer to me now. 
These are all html5 video but under iframe.

**Comment by ste-xx** [comment]
I see.
Maybe following helps:
In 
plussub/src/background/platform/onPageActionClicked/chrome/index.ts

 You can change

`chrome.pageAction.onClicked.addListener(() => chrome.tabs.executeScript({ file: 'dist/popup.js' }));`

To

`chrome.pageAction.onClicked.addListener(() => chrome.tabs.executeScript({ file: 'dist/popup.js' , allFrames: true}));`

Which should injects the popup into all iframes. 

Sry for the bad formatting, I write this from my phone.

**Comment by cyj98** [comment]
It can work on the first website now. But It will popup two windows(one for page, one for video).
It still cannot work on the second and the third website.

**Comment by cyj98** [comment]
I find that the video can be detected under content_script. Maybe I should move some function to that.

**Comment by cyj98** [comment]
It works now. I just try to add the "<all_urls>" permission in the manifest.json: 
"permissions": [
    "<all_urls>"
]
But it would show popup on both iframe page and parent. I am working on making it show popup only on the parent page.
